Building DAG of jobs...
Your conda installation is not configured to use strict channel priorities. This is however crucial for having robust and correct environments (for details, see https://conda-forge.org/docs/user/tipsandtricks.html). Please consider to configure strict priorities by executing 'conda config --set channel_priority strict'.
Creating conda environment envs/metabat2_env.yaml...
Downloading and installing remote packages.
Full Traceback (most recent call last):
  File "/cfs/klemming/home/e/erikzhi/.conda/envs/magpipe/lib/python3.11/site-packages/snakemake/deployment/conda.py", line 590, in create
    out = create_env(env_file, filetype="yaml")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cfs/klemming/home/e/erikzhi/.conda/envs/magpipe/lib/python3.11/site-packages/snakemake/deployment/conda.py", line 552, in create_env
    out = shell.check_output(
          ^^^^^^^^^^^^^^^^^^^
  File "/cfs/klemming/home/e/erikzhi/.conda/envs/magpipe/lib/python3.11/site-packages/snakemake/shell.py", line 63, in check_output
    return sp.check_output(cmd, shell=True, executable=executable, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cfs/klemming/home/e/erikzhi/.conda/envs/magpipe/lib/python3.11/subprocess.py", line 465, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cfs/klemming/home/e/erikzhi/.conda/envs/magpipe/lib/python3.11/subprocess.py", line 569, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'mamba env create --quiet --file "/cfs/klemming/scratch/e/erikzhi/project/magpipe-master/.snakemake/conda/a5817b11a651520de7b2e69088713781_.yaml" --prefix "/cfs/klemming/scratch/e/erikzhi/project/magpipe-master/.snakemake/conda/a5817b11a651520de7b2e69088713781_"' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cfs/klemming/home/e/erikzhi/.conda/envs/magpipe/lib/python3.11/site-packages/snakemake/__init__.py", line 760, in snakemake
    success = workflow.execute(
              ^^^^^^^^^^^^^^^^^
  File "/cfs/klemming/home/e/erikzhi/.conda/envs/magpipe/lib/python3.11/site-packages/snakemake/workflow.py", line 930, in execute
    dag.create_conda_envs(
  File "/cfs/klemming/home/e/erikzhi/.conda/envs/magpipe/lib/python3.11/site-packages/snakemake/dag.py", line 354, in create_conda_envs
    env.create(dryrun)
  File "/cfs/klemming/home/e/erikzhi/.conda/envs/magpipe/lib/python3.11/site-packages/snakemake/deployment/conda.py", line 609, in create
    raise CreateCondaEnvironmentException(
snakemake.exceptions.CreateCondaEnvironmentException: Could not create conda environment from /cfs/klemming/scratch/e/erikzhi/project/magpipe-master/envs/metabat2_env.yaml:
Command:
mamba env create --quiet --file "/cfs/klemming/scratch/e/erikzhi/project/magpipe-master/.snakemake/conda/a5817b11a651520de7b2e69088713781_.yaml" --prefix "/cfs/klemming/scratch/e/erikzhi/project/magpipe-master/.snakemake/conda/a5817b11a651520de7b2e69088713781_"
Output:
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Installing pip dependencies: ...working... Pip subprocess error:
Traceback (most recent call last):
  File "/cfs/klemming/scratch/e/erikzhi/project/magpipe-master/.snakemake/conda/a5817b11a651520de7b2e69088713781_/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/cfs/klemming/scratch/e/erikzhi/project/magpipe-master/.snakemake/conda/a5817b11a651520de7b2e69088713781_/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/pdc/software/22.06/eb/software/reframe/4.0.1/external/pip/__main__.py", line 29, in <module>
    from pip._internal.cli.main import main as _main
  File "/pdc/software/22.06/eb/software/reframe/4.0.1/external/pip/_internal/cli/main.py", line 9, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/pdc/software/22.06/eb/software/reframe/4.0.1/external/pip/_internal/cli/autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/pdc/software/22.06/eb/software/reframe/4.0.1/external/pip/_internal/cli/main_parser.py", line 9, in <module>
    from pip._internal.build_env import get_runnable_pip
  File "/pdc/software/22.06/eb/software/reframe/4.0.1/external/pip/_internal/build_env.py", line 20, in <module>
    from pip._internal.cli.spinners import open_spinner
  File "/pdc/software/22.06/eb/software/reframe/4.0.1/external/pip/_internal/cli/spinners.py", line 9, in <module>
    from pip._internal.utils.logging import get_indentation
  File "/pdc/software/22.06/eb/software/reframe/4.0.1/external/pip/_internal/utils/logging.py", line 8, in <module>
    from dataclasses import dataclass
ModuleNotFoundError: No module named 'dataclasses'

failed

CondaEnvException: Pip failed



CreateCondaEnvironmentException:
Could not create conda environment from /cfs/klemming/scratch/e/erikzhi/project/magpipe-master/envs/metabat2_env.yaml:
Command:
mamba env create --quiet --file "/cfs/klemming/scratch/e/erikzhi/project/magpipe-master/.snakemake/conda/a5817b11a651520de7b2e69088713781_.yaml" --prefix "/cfs/klemming/scratch/e/erikzhi/project/magpipe-master/.snakemake/conda/a5817b11a651520de7b2e69088713781_"
Output:
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Installing pip dependencies: ...working... Pip subprocess error:
Traceback (most recent call last):
  File "/cfs/klemming/scratch/e/erikzhi/project/magpipe-master/.snakemake/conda/a5817b11a651520de7b2e69088713781_/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/cfs/klemming/scratch/e/erikzhi/project/magpipe-master/.snakemake/conda/a5817b11a651520de7b2e69088713781_/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/pdc/software/22.06/eb/software/reframe/4.0.1/external/pip/__main__.py", line 29, in <module>
    from pip._internal.cli.main import main as _main
  File "/pdc/software/22.06/eb/software/reframe/4.0.1/external/pip/_internal/cli/main.py", line 9, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/pdc/software/22.06/eb/software/reframe/4.0.1/external/pip/_internal/cli/autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/pdc/software/22.06/eb/software/reframe/4.0.1/external/pip/_internal/cli/main_parser.py", line 9, in <module>
    from pip._internal.build_env import get_runnable_pip
  File "/pdc/software/22.06/eb/software/reframe/4.0.1/external/pip/_internal/build_env.py", line 20, in <module>
    from pip._internal.cli.spinners import open_spinner
  File "/pdc/software/22.06/eb/software/reframe/4.0.1/external/pip/_internal/cli/spinners.py", line 9, in <module>
    from pip._internal.utils.logging import get_indentation
  File "/pdc/software/22.06/eb/software/reframe/4.0.1/external/pip/_internal/utils/logging.py", line 8, in <module>
    from dataclasses import dataclass
ModuleNotFoundError: No module named 'dataclasses'

failed

CondaEnvException: Pip failed


unlocking
removing lock
removing lock
removed all locks
